import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { login, auth } from "../firebase";
import { sendPasswordResetEmail } from "firebase/auth";
import NavBar from "../components/NavBar";
import step1Icon from "../assets/steps/Step 1.svg";
import step2Icon from "../assets/steps/Step 2.svg";
import step3Icon from "../assets/steps/Step 3.svg";
import textboxLoginBg from "../assets/textbox_login.svg";
import eyeIcon from "../assets/eye.svg"; // 👈 your eye icon
import signinBg from "../assets/signin_button.svg";
import ForgotPassword from "../views/forgotPassword"
export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string|null>(null);
  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);
  const [showForgotModal, setShowForgotModal] = useState(false);
  const [modalState, setModalState] = useState<"input" | "success">("input");

  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await login(email, password);
      navigate("/Upload");
      // navigate("/AASequence");
      //navigate("/SeqGenerator");
      //navigate("/Generating");
    } catch (err: any) {
      setError(err.message);
    }
  };
  
  useEffect(() => {
    const remembered = localStorage.getItem("rememberMe") === "true";
    const savedEmail = localStorage.getItem("userEmail");

    if (remembered && savedEmail) {
      setEmail(savedEmail);
      setRememberMe(true);
    }
  }, []);

  const handleSendResetEmail = async (email: string) => {
  if (!email) {
    setError("Please enter your email to reset your password.");
    return;
  }
  try {
    await sendPasswordResetEmail(auth, email);
    setModalState("success");
  } catch (err: any) {
    setError(err.message);
  }
};

  return (
    <div style={{ height: "100vh", position: "relative" }}>
      {/* Navbar overlays at the top, doesn’t consume flex space */}
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, zIndex: 10 }}>
        <NavBar />
      </div>

      {/* Split screen container */}
      <div style={{ display: "flex", height: "100%" }}>
      {/* Left blue panel */}
      <div
        style={{
          flex: 1,
          background: "#007bff",
          color: "white",
          padding: "2rem",
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-start",
          paddingTop: "15vh",
          fontFamily: "Inter"
        }}
      >
        <h1 className="heading-xl">GENERATE A <br /> PATENT APPLICATION <br />IN 3 EASY STEPS</h1>
        <div
          className="paragraph-xl"
          style={{ marginRight: "2rem", lineHeight: "1.6", fontSize: "48"}}
        >
          <p>
            <img
              src={step1Icon}
              alt="Step 1"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Sign in
          </p>
          <p>
            <img
              src={step2Icon}
              alt="Step 2"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Upload invention documents
          </p>
          <p>
            <img
              src={step3Icon}
              alt="Step 3"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Download your patent application generated by our AI
          </p>
        </div>
      </div>

      {/* Right login form */}
      <div
        style={{
          flex: 1,
          display: "flex",
          justifyContent: "center",
          paddingTop: "20vh",
        }}
      >
        <form
          onSubmit={handleSubmit}
          style={{
            width: "300px",
            display: "flex",
            flexDirection: "column",
            gap: "18px",
          }}
        >
          {/* Email box */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${textboxLoginBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              color: "#9ca3af",
              fontSize: "15px",
            }}
          >
            <input
              type="email"
              placeholder="Enter email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
                fontSize: "15px",
                color: "#9ca3af",
              }}
            />
          </div>

          {/* Password box */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${textboxLoginBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              color: "#9ca3af",
              fontSize: "15px",
              position: "relative",
              marginTop: "-20px",
            }}
          >
            <input
              type={showPassword ? "text" : "password"}
              placeholder="Enter password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
                fontSize: "15px",
                color: "#9ca3af",
              }}
            />
            <img
              src={eyeIcon}
              alt="Toggle password visibility"
              className = "button-hover"
              onClick={() => setShowPassword((prev) => !prev)}
              style={{
                position: "absolute",
                right: "16px",
                top: "50%",
                transform: "translateY(-50%)",
                height: "24px",
                width: "24px",
                cursor: "pointer",
              }}
            />
          </div>
          {/* Remember me + forgot password */}        
          <span
            className = "button-hover"
            onClick={() => setShowForgotModal(true)}
            style={{
              color: "#007bff",
              cursor: "pointer",
              fontFamily: "'Inter', sans-serif",
              marginTop: "-20px",
              fontSize: "15px",
            }}
          >
            Forgot password?
          </span>

          <label style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <input
              type="checkbox"
              checked={rememberMe}
              onChange={(e) => setRememberMe(e.target.checked)}
            />
            Remember my email 
          </label>

          {/* {error && <p style={{ color: "red" }}>{error}</p>} */}
          
          {error && (
            <p style={{ color: "red" }}>
              Invalid credentials, try again.
            </p>
          )}
          {/* Sign in button */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${signinBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              fontSize: "15px",
              position: "relative",
              cursor: "pointer",
            }}
          >
            <div
              role="button"
              tabIndex={0}
              className = "button-hover"
              onClick={handleSubmit}
              onKeyDown={(e) => e.key === "Enter" && handleSubmit(e)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
              }}
            ></div>

            {/* Hidden button for Enter */}
            <button type="submit" style={{ display: "none" }}></button>
          </div>
          <ForgotPassword
              isOpen={showForgotModal}
              onClose={() => {
                setShowForgotModal(false);
                setModalState("input");
                setError(null);
              }}
              onSendReset={handleSendResetEmail}
              email={email}
              setEmail={setEmail}
              error={error}
              modalState={modalState}
              setModalState={setModalState}
            />
        </form>
      </div>
    </div>
    </div>
  );
}