import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { login, auth } from "../firebase";
import { sendPasswordResetEmail } from "firebase/auth";
import NavBar from "../components/NavBar";
import step1Icon from "../assets/steps/Step 1.svg";
import step2Icon from "../assets/steps/Step 2.svg";
import step3Icon from "../assets/steps/Step 3.svg";
import textboxLoginBg from "../assets/textbox_login.svg";
import eyeIcon from "../assets/eye.svg"; // 👈 your eye icon
import signinBg from "../assets/signin_button.svg";
export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string|null>(null);
  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);

  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await login(email, password);
      navigate("/Upload");
    } catch (err: any) {
      setError(err.message);
    }
  };


  const handleForgotPassword = async () => {
    if (!email) {
      setError("Please enter your email to reset your password.");
      return;
    }
    try {
      await sendPasswordResetEmail(auth, email);
      alert("Password reset email sent!");
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div style={{ height: "100vh", position: "relative" }}>
      {/* Navbar overlays at the top, doesn’t consume flex space */}
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, zIndex: 10 }}>
        <NavBar />
      </div>

      {/* Split screen container */}
      <div style={{ display: "flex", height: "100%" }}>
      {/* Left blue panel */}
      <div
        style={{
          flex: 1,
          background: "#007bff",
          color: "white",
          padding: "2rem",
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-start",
          paddingTop: "15vh",
        }}
      >
        <h1 className="heading-xl">GENERATE A PATENT APPLICATION IN 3 EASY STEPS</h1>
        <div
          className="paragraph-xl"
          style={{ marginRight: "2rem", lineHeight: "1.6" }}
        >
          <p>
            <img
              src={step1Icon}
              alt="Step 1"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Sign in
          </p>
          <p>
            <img
              src={step2Icon}
              alt="Step 2"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Upload invention documents
          </p>
          <p>
            <img
              src={step3Icon}
              alt="Step 3"
              style={{ height: "42px", marginRight: "12px", marginTop: "2px" }}
            />
            Download your patent application generated by our AI
          </p>
        </div>
      </div>

      {/* Right login form */}
      <div
        style={{
          flex: 1,
          display: "flex",
          justifyContent: "center",
          paddingTop: "20vh",
        }}
      >
        <form
          onSubmit={handleSubmit}
          style={{
            width: "300px",
            display: "flex",
            flexDirection: "column",
            gap: "18px",
          }}
        >
          {/* Email box */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${textboxLoginBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              color: "#9ca3af",
              fontSize: "15px",
            }}
          >
            <input
              type="email"
              placeholder="Enter email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
                fontSize: "15px",
                color: "#9ca3af",
              }}
            />
          </div>

          {/* Password box */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${textboxLoginBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              color: "#9ca3af",
              fontSize: "15px",
              position: "relative",
              marginTop: "-20px",
            }}
          >
            <input
              type={showPassword ? "text" : "password"}
              placeholder="Enter password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
                fontSize: "15px",
                color: "#9ca3af",
              }}
            />
            <img
              src={eyeIcon}
              alt="Toggle password visibility"
              onClick={() => setShowPassword(!showPassword)}
              style={{
                position: "absolute",
                right: "16px",
                top: "50%",
                transform: "translateY(-50%)",
                height: "24px",
                width: "24px",
                cursor: "pointer",
              }}
            />
          </div>

          

          {/* Remember me + forgot password */}
                    
                  
          <span
            onClick={handleForgotPassword}
            style={{
              color: "#007bff",
              cursor: "pointer",
              fontFamily: "'Inter', sans-serif",
              marginTop: "-20px",
              fontSize: "15px",
            }}
          >
            Forgot password?
          </span>

          <label style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <input
              type="checkbox"
              checked={rememberMe}
              onChange={(e) => setRememberMe(e.target.checked)}
            />
            Remember this device
          </label>


          {error && <p style={{ color: "red" }}>{error}</p>}

          {/* Sign in button */}
          <div
            style={{
              width: "100%",
              height: "80px",
              backgroundImage: `url(${signinBg})`,
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
              backgroundPosition: "center",
              display: "flex",
              alignItems: "center",
              padding: "0 16px",
              fontSize: "15px",
              position: "relative",
              cursor: "pointer",
            }}
          >
            <div
              role="button"
              tabIndex={0}
              onClick={handleSubmit}
              onKeyDown={(e) => e.key === "Enter" && handleSubmit(e)}
              style={{
                flex: 1,
                height: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
              }}
            ></div>

            {/* Hidden button for Enter */}
            <button type="submit" style={{ display: "none" }}></button>
          </div>
        </form>
      </div>
    </div>
    </div>
  );
}